#!/usr/bin/env bash
# Every public repository in the markup-carve organization is either LISTED in
# README.md or NAMED here as deliberately out of scope.
#
# Why a script rather than care: three repos (carve-sile, sublime-carve-lsp,
# zensical-carve-demo) were absent on 2026-08-21 and nothing noticed. A curated
# list that silently omits its own org's work is worse than an uncurated one,
# because a reader treats the absence as a statement.
#
# Needs `gh` authenticated. Skips (exit 0) without it, so a fork's CI does not
# fail on a missing token.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
README="${HERE}/README.md"

# Deliberately unlisted, with the reason. Anything not here must be in README.md.
#
#   awesome-carve         - this list itself
#   .github               - org profile and community health files, not a project
#   homebrew-carve        - a Homebrew tap. Its formula is generated by
#                           carve-rs's release workflow and lands on the first
#                           release that ships binaries; list it under Tools
#                           once `brew install markup-carve/carve/carve` works.
#   docusaurus-carve      - scaffolded 2026-08-21, no code yet.
#   obsidian-carve        - scaffolded 2026-08-21, no code yet.
#   webpack-loader-carve  - scaffolded 2026-08-21, no code yet.
#
# The three scaffolds are exempt because a curated list that points a reader at
# an empty repository is worse than one that omits it. Move each into README.md
# in the same change that gives it something to install, and delete its line
# here - that pairing is the point of listing them by name rather than adding a
# blanket "skip empty repos" rule.
declare -a EXEMPT=(
  "awesome-carve"
  ".github"
  "homebrew-carve"
  "docusaurus-carve"
  "obsidian-carve"
  "webpack-loader-carve"
)

if ! command -v gh > /dev/null 2>&1 || ! gh auth status > /dev/null 2>&1; then
  echo "SKIP: gh is unavailable or unauthenticated"
  exit 0
fi

mapfile -t repos < <(gh repo list markup-carve --limit 200 --no-archived --visibility public \
  --json name --jq '.[].name' | sort)

if [ "${#repos[@]}" -eq 0 ]; then
  echo "FAIL: the org listing came back empty; refusing to report success"
  exit 1
fi

missing=()
for repo in "${repos[@]}"; do
  skip=false
  for exempt in "${EXEMPT[@]}"; do
    if [ "${repo}" = "${exempt}" ]; then
      skip=true
      break
    fi
  done
  if [ "${skip}" = true ]; then
    continue
  fi
  # Match the org-qualified path, so a bare word in prose cannot satisfy this.
  if ! grep -qF "markup-carve/${repo}" "${README}"; then
    missing+=("${repo}")
  fi
done

if [ "${#missing[@]}" -gt 0 ]; then
  echo "FAIL: ${#missing[@]} public repo(s) are neither listed in README.md nor exempt:"
  for repo in "${missing[@]}"; do
    echo "  - markup-carve/${repo}"
  done
  echo
  echo "Add each to the section it belongs in, or add it to EXEMPT in $(basename "${BASH_SOURCE[0]}") with the reason."
  exit 1
fi

echo "ok: ${#repos[@]} public repos, all listed or exempt"
